---
output:
  pdf_document: default
  html_document: default
  word_document: default
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# KDExp: Kernel Density Estimation Prior Distribution for Exposure Uncertainty Propagation 

## KDExp_Example

[1] Load the simulated data: 
```{r}
set.seed(8453)

library(KDExp)
library(kernelboot)
load("C:\\Users\\jlw98\\Desktop\\Yale Research\\Created R Packages\\KDExp\\KDExp_Example\\simulated_data.RData")

y<-sim_data[[1]]
x<-matrix(1,
          nrow = length(y),
          ncol = 1)
z_ppd<-sim_data[[2]]
dim(z_ppd)
```

[2] Fit the Models:

```{r echo=TRUE}
##########################
#UKDE Bandwidth Estimation
##########################
h<-rep(0.00,
       times = length(y))
for(k in 1:length(y)){
   h[k]<-bw.SJ(z_ppd[k,])
   }

##########################
#MKDE Bandwidth Estimation
##########################
H<-bw.scott(t(z_ppd))
   
###############################################
#Model Fitting
###############################################
burnin<-1000
mcmc_samples<-6000
thin<-10
keep_set<-seq((burnin + 1),
              mcmc_samples,
              thin)

results_ukde<-UKDE(mcmc_samples = mcmc_samples,
                   y = y,
                   x = x, 
                   z_ppd = z_ppd,
                   h = h,
                   likelihood_indicator = 1)

results_mkde<-MKDE(mcmc_samples = mcmc_samples,
                   y = y,
                   x = x, 
                   z_ppd = z_ppd,
                   H = H,
                   likelihood_indicator = 1)

```

[3]  Analyzing Output:

```{r echo=TRUE}
plot(results_ukde$theta[keep_set,1], type="l")
lines(results_mkde$theta[keep_set,1], col = "red")
```

