# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MKDE <- function(mcmc_samples, y, x, z_ppd, H, likelihood_indicator, offset = NULL, trials = NULL, a_r_prior = NULL, b_r_prior = NULL, a_sigma2_epsilon_prior = NULL, b_sigma2_epsilon_prior = NULL, sigma2_regress_prior = NULL, r_init = NULL, sigma2_epsilon_init = NULL, beta_init = NULL, theta_init = NULL) {
    .Call(`_KDExp_MKDE`, mcmc_samples, y, x, z_ppd, H, likelihood_indicator, offset, trials, a_r_prior, b_r_prior, a_sigma2_epsilon_prior, b_sigma2_epsilon_prior, sigma2_regress_prior, r_init, sigma2_epsilon_init, beta_init, theta_init)
}

UKDE <- function(mcmc_samples, y, x, z_ppd, h, likelihood_indicator, offset = NULL, trials = NULL, a_r_prior = NULL, b_r_prior = NULL, a_sigma2_epsilon_prior = NULL, b_sigma2_epsilon_prior = NULL, sigma2_regress_prior = NULL, r_init = NULL, sigma2_epsilon_init = NULL, beta_init = NULL, theta_init = NULL) {
    .Call(`_KDExp_UKDE`, mcmc_samples, y, x, z_ppd, h, likelihood_indicator, offset, trials, a_r_prior, b_r_prior, a_sigma2_epsilon_prior, b_sigma2_epsilon_prior, sigma2_regress_prior, r_init, sigma2_epsilon_init, beta_init, theta_init)
}

delta_update <- function(x, off_set, n, p_x, sigma2_regress, w, gamma, z_old) {
    .Call(`_KDExp_delta_update`, x, off_set, n, p_x, sigma2_regress, w, gamma, z_old)
}

neg_two_loglike_update <- function(y, x, off_set, tri_als, likelihood_indicator, n, r, sigma2_epsilon, beta, theta, z) {
    .Call(`_KDExp_neg_two_loglike_update`, y, x, off_set, tri_als, likelihood_indicator, n, r, sigma2_epsilon, beta, theta, z)
}

r_update <- function(y, x, off_set, n, a_r, b_r, beta_old, theta_old, z_old) {
    .Call(`_KDExp_r_update`, y, x, off_set, n, a_r, b_r, beta_old, theta_old, z_old)
}

rcpp_pgdraw <- function(b, c) {
    .Call(`_KDExp_rcpp_pgdraw`, b, c)
}

sigma2_epsilon_update <- function(y, x, n, a_sigma2_epsilon, b_sigma2_epsilon, beta_old, theta_old, z_old) {
    .Call(`_KDExp_sigma2_epsilon_update`, y, x, n, a_sigma2_epsilon, b_sigma2_epsilon, beta_old, theta_old, z_old)
}

w_update <- function(y, x, off_set, tri_als, likelihood_indicator, n, r, beta_old, theta_old, z_old) {
    .Call(`_KDExp_w_update`, y, x, off_set, tri_als, likelihood_indicator, n, r, beta_old, theta_old, z_old)
}

z_MKDE_update <- function(x, z_ppd, H_inv, off_set, n, m, w, gamma, beta, theta) {
    .Call(`_KDExp_z_MKDE_update`, x, z_ppd, H_inv, off_set, n, m, w, gamma, beta, theta)
}

z_UKDE_update <- function(x, z_ppd, h, off_set, n, m, w, gamma, beta, theta) {
    .Call(`_KDExp_z_UKDE_update`, x, z_ppd, h, off_set, n, m, w, gamma, beta, theta)
}

